spring.application.name=demo
spring.datasource.url=jdbc:postgresql://postgres:5432/task-manager
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=my-secret-key

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

api.cors.allowed-origins=${API_CORS_ALLOWED_ORIGINS:http://localhost:4200}